// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBose5NzyyCHQXPECLZCIB_LNdQlFok--I',
    appId: '1:716750532585:web:8d15eecfbc9d1b5ff86578',
    messagingSenderId: '716750532585',
    projectId: 'hopeful-hold-387912',
    authDomain: 'hopeful-hold-387912.firebaseapp.com',
    storageBucket: 'hopeful-hold-387912.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumR7wxy1jNnQNpX_6gH0IUQZKYipY9mU',
    appId: '1:716750532585:android:8993d71e8336a6c5f86578',
    messagingSenderId: '716750532585',
    projectId: 'hopeful-hold-387912',
    storageBucket: 'hopeful-hold-387912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzgnVOTROJOauYcRaSpZsey1WTqD_j61s',
    appId: '1:716750532585:ios:708ebf9b208074a2f86578',
    messagingSenderId: '716750532585',
    projectId: 'hopeful-hold-387912',
    storageBucket: 'hopeful-hold-387912.appspot.com',
    iosBundleId: 'com.KareemJaradah.chatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzgnVOTROJOauYcRaSpZsey1WTqD_j61s',
    appId: '1:716750532585:ios:2783f23203d2b109f86578',
    messagingSenderId: '716750532585',
    projectId: 'hopeful-hold-387912',
    storageBucket: 'hopeful-hold-387912.appspot.com',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBose5NzyyCHQXPECLZCIB_LNdQlFok--I',
    appId: '1:716750532585:web:6c48e31c0bc30639f86578',
    messagingSenderId: '716750532585',
    projectId: 'hopeful-hold-387912',
    authDomain: 'hopeful-hold-387912.firebaseapp.com',
    storageBucket: 'hopeful-hold-387912.appspot.com',
  );

}